[versions]
agp = "9.0.1"
appcompat = "1.7.1"
preference = "1.2.1"
colorpicker = "1.1.0"
gitchangelog = "3.1.2"
grgit = "5.3.3"
kotlin = "2.3.10"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
gitChangelog = { id = "se.bjurr.gitchangelog.git-changelog-gradle-plugin", version.ref = "gitchangelog" }
grGit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
jaredrummler-colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpicker" }
jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }